= uProtocol CloudEvents
:toc:
:sectnums:


== Overview

https://github.com/eclipse-uprotocol/uprotocol-spec/blob/main/up-l1/cloudevents.adoc[uProtocol CloudEvents] is a common message envelope that could be used to carry way to represent uProtocol transport layer information `UUri` (source), `UPayload`, and `UAttributes`. `CloudEvents` are used by a number of Device-2-Cloud and Cloud-2-Device based transports such as MQTT and HTTP, however it could also be used by any transport (ex. Binder). 

NOTE: CloudEvent is not, nor was not, meant to be _the_ only message format used below or above the transport layer.

=== CloudEventFactory
Factory class that builds the various types of CloudEvents for uProtocol (publish, notification, request, response)

== Examples

The SDK contains comprehensive tests, the best place to look at how all the APIs are used are at:

* link:src/test/java/org/eclipse/uprotocol/uri/factory/UriFactoryTest.java[UriFactoryTest.java]

* link:src/test/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactoryTest.java[CloudEventFactoryTest.java]
