name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with: # configure settings.xml
        distribution: 'temurin'
        java-version: '17'
        server-id: ossrh
        server-username: OSSRH_USER
        server-password: OSSRH_PASSWORD

    - name: Build and Publish to OSSRH snapshot repo
      run: mvn clean deploy
      env:
        OSSRH_USER: ${{ secrets.ORG_OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.ORG_OSSRH_PASSWORD }}
